version: "3.9"
services:
  server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    environment:
      - DISCORD_CLIENT_PRIVATE=${DISCORD_CLIENT_PRIVATE:?your client private not set}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID:?your discord channel id not set}